# Generated by Django 4.1 on 2022-08-16 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_created_vote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='vote',
            new_name='voter',
        ),
    ]
